# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ganda < Formula
  desc "fast cmd-line app that quickly request millions of urls and save/echo the results"
  homepage "https://github.com/tednaleid/ganda"
  version "1.0.0"

  on_macos do
    on_intel do
      url "https://github.com/tednaleid/ganda/releases/download/v1.0.0/ganda_Darwin_x86_64.tar.gz"
      sha256 "88e1f30eff91990983779f0d33284bd3d40f35cb3959d9abe26a36071bb83928"

      def install
        bin.install "ganda"
      end
    end
    on_arm do
      url "https://github.com/tednaleid/ganda/releases/download/v1.0.0/ganda_Darwin_arm64.tar.gz"
      sha256 "b26b0057b1106fc030af4e290920f117b88b1b2182aa389e51ddef21bf9c7ef2"

      def install
        bin.install "ganda"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tednaleid/ganda/releases/download/v1.0.0/ganda_Linux_x86_64.tar.gz"
        sha256 "58cef5445fe08671b92c5b96f62c923957f8f1599d120c72bf579f546dfde84c"

        def install
          bin.install "ganda"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tednaleid/ganda/releases/download/v1.0.0/ganda_Linux_arm64.tar.gz"
        sha256 "55040ddaf3e5d0c22038e0c27187a6a6f13de5ed1d779d1fcfbc7080972c2872"

        def install
          bin.install "ganda"
        end
      end
    end
  end
end
