# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ganda < Formula
  desc "fast cmd-line app that quickly request millions of urls and save/echo the results"
  homepage "https://github.com/tednaleid/ganda"
  version "1.0.1"

  on_macos do
    on_intel do
      url "https://github.com/tednaleid/ganda/releases/download/v1.0.1/ganda_Darwin_x86_64.tar.gz"
      sha256 "81689a74f8f4a8443ff5feeacb0d0f0422567190106b7037453630dcd223d545"

      def install
        bin.install "ganda"
      end
    end
    on_arm do
      url "https://github.com/tednaleid/ganda/releases/download/v1.0.1/ganda_Darwin_arm64.tar.gz"
      sha256 "3e3e1e14103ce1377a9200de37de2a66eac8605780ad90567b68b5bddb324a46"

      def install
        bin.install "ganda"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tednaleid/ganda/releases/download/v1.0.1/ganda_Linux_x86_64.tar.gz"
        sha256 "bb1fcc66f2beba87a131258355245cef66fa893b6ff908b8d6045b326bbb86fa"

        def install
          bin.install "ganda"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tednaleid/ganda/releases/download/v1.0.1/ganda_Linux_arm64.tar.gz"
        sha256 "a4eb0d305180bb90e03ab276935952efb4a425ea6c47e0c1730f7d8f24c81cfa"

        def install
          bin.install "ganda"
        end
      end
    end
  end
end
