# This file was generated by GoReleaser. DO NOT EDIT.
class Ganda < Formula
  desc "fast cmd-line app that quickly request millions of urls and save/echo the results"
  homepage "https://github.com/tednaleid/ganda"
  version "0.1.9"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/tednaleid/ganda/releases/download/v0.1.9/ganda_0.1.9_darwin_amd64.tar.gz"
    sha256 "bfdf60911f4dd8541e3fe8e08eca9d6fcadadfe55693afe0ca9fe283d314ae9b"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/tednaleid/ganda/releases/download/v0.1.9/ganda_0.1.9_linux_amd64.tar.gz"
      sha256 "57a86b05a90a59667da2e495de63049193f0a1eee24d33f20ce23a80be5b7a53"
    end
  end

  def install
    bin.install "ganda"
  end
end
