# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ganda < Formula
  desc "fast cmd-line app that quickly request millions of urls and save/echo the results"
  homepage "https://github.com/tednaleid/ganda"
  version "1.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tednaleid/ganda/releases/download/v1.1.0/ganda_Darwin_x86_64.tar.gz"
      sha256 "9df43990529d9d0f2275bd39531fa95c7dc80262089dac35173d566016228d8b"

      define_method(:install) do
        bin.install "ganda"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tednaleid/ganda/releases/download/v1.1.0/ganda_Darwin_arm64.tar.gz"
      sha256 "02d0016cbb4fb48099cb6b82f7a0fbe33716f2933ba8b318ddb328b5aca8724c"

      define_method(:install) do
        bin.install "ganda"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tednaleid/ganda/releases/download/v1.1.0/ganda_Linux_x86_64.tar.gz"
      sha256 "2412774fff235840ee02a8acb842cd96b427cd8dc64ba725496348c2831fcdb0"
      define_method(:install) do
        bin.install "ganda"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tednaleid/ganda/releases/download/v1.1.0/ganda_Linux_arm64.tar.gz"
      sha256 "15f1367f3f2e45de98a38382968cb943c8ffab9995a1132d441af1836db9b7f9"
      define_method(:install) do
        bin.install "ganda"
      end
    end
  end
end
